name: Luacheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: |
          luarocks install luacheck

      - name: Lint
        run: make luacheck
