name: Luacheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install luacheck
        run: |
          luarocks install luacheck

      - name: Lint
        run: make luacheck
