name: Luacheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LuaRocks
        # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
        uses: ColinKennedy/gh-actions-luarocks@v1.0.0

      - name: Print LuaRocks Version
        run: luarocks --version

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Print Luacheck Version
        run: luacheck --version

      - name: Lint
        run: make luacheck
